# This file was generated by GoReleaser. DO NOT EDIT.
cask "localhost-top" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "93027b075413b0210bc68fc779a17c4b435a51931b00584904cc590b6a406b53"
      url "https://github.com/Hol1kgmg/homebrew-localhost-top/releases/download/v#{version}/localhost-top_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "db3d044b8f941629af5e3e420dc3c69d9f1884bcb1d63f61921276e98e629f39"
      url "https://github.com/Hol1kgmg/homebrew-localhost-top/releases/download/v#{version}/localhost-top_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "localhost-top"
  desc "vimキーバインドでlocalhostのLISTENプロセスを一覧・kill・操作するTUIツール"
  homepage "https://github.com/Hol1kgmg/homebrew-localhost-top"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localhost-top"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-l", "#{staged_path}/localhost-top"]).stdout.include? "com.apple.quarantine"
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/localhost-top"]
    end
  end

  # No zap stanza required

end
