# This file was generated by GoReleaser. DO NOT EDIT.
cask "localhost-top" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "97ab3ce9fc1fd5a45f8ddd65a5de91536ab0dbc34ed2fb79f818721ba0a0e5cc"
      url "https://github.com/Hol1kgmg/homebrew-localhost-top/releases/download/v#{version}/localhost-top_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5de92ac4ce20f8226692879170d2d4346c8f6e1c2aa09a2144c51b847320d483"
      url "https://github.com/Hol1kgmg/homebrew-localhost-top/releases/download/v#{version}/localhost-top_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "localhost-top"
  desc "vimキーバインドでlocalhostのLISTENプロセスを一覧・kill・操作するTUIツール"
  homepage "https://github.com/Hol1kgmg/homebrew-localhost-top"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localhost-top"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-l", "#{staged_path}/localhost-top"]).stdout.include? "com.apple.quarantine"
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/localhost-top"]
    end
  end

  # No zap stanza required

end
