# This file was generated by GoReleaser. DO NOT EDIT.
cask "localhost-top" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "d421ee59ac9601c0d61cbb82ac6daa011031aca334a0058d1f4e25d16a35f0d7"
      url "https://github.com/Hol1kgmg/homebrew-localhost-top/releases/download/v#{version}/localhost-top_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6fca539d2e646c0cb1118ad233b37ec6e1e15b31418b0a6eb31a950c4423a3cc"
      url "https://github.com/Hol1kgmg/homebrew-localhost-top/releases/download/v#{version}/localhost-top_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "localhost-top"
  desc "vimキーバインドでlocalhostのLISTENプロセスを一覧・kill・操作するTUIツール"
  homepage "https://github.com/Hol1kgmg/homebrew-localhost-top"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localhost-top"

  # No zap stanza required

end
